---
- name: Install useful packages
  apt:
    name:
      - python
      - python3
      - python3-pip
      - openjdk-8-jdk
      - git
    update_cache: yes

- name: Clone Repositorios
  git:
    repo: "{{item.url_repo}}"
    dest: "{{item.dest_repo}}"
    update: no
  loop: "{{repository}}"
