- name: "Provision kathara"
  hosts: kathara
  become: yes
  roles:
    - role: kathara
      vars:
        - user_name: kathara
    - role: classroom
      vars:
        repository:
          [
            {
              url_repo: "https://github.com/KatharaFramework/Kathara-Labs.git",
              dest_repo: "/home/kathara/Kathara-Labs",
            },
          ]
